# This is a basic workflow to help you get started with Actions

name: DevopsUipath

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  print-details:
    runs-on: windows-latest
    steps:
      - name: Test1
        run: |
          New-Item -Path "C:\\" -ItemType "directory" -Name "scripts";
          Invoke-WebRequest "https://github.com/Bsomrani/Uipath_GitHubActionTest/blob/main/Test_Uipath_CICD_Auchan/scripts/UiPathPack.ps1" -OutFile "C:\\scripts\\UiPathPack.ps1";
