# This is a basic workflow to help you get started with Actions

name: DevopsUipath

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env :
  PROJECT_NAME: Uipath_GitHubActionTest
  PROJECT_FOLDER: ${{ github.action_path }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  print-details:
    runs-on: windows-latest
    steps:
      - name: echo-default-env-variables
        shell: pwsh
        run: |
          echo "Home: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          
  
